name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_TAG=bhoobal/useradminapi:$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_TAG
        docker push $IMAGE_TAG
        
